### ISSUE TITLE
Allow collapsing whole sections

### ISSUE THREAD

**Issue by segfaultxavi** [MathewSachin/docfx-tmpl#1]
I love that you can collapse individual methods and properties.
I have tweaked the default template myself to be able to collapse the **inherits** and **implements** h4 sections, but so far, I have not succeeded in collapsing the h3 sections Constructors, Fields, Properties, Methods...

Do you have any idea on how to achieve that?

Thanks!

**Comment by MathewSachin** [comment]
See this patch: https://github.com/MathewSachin/docfx-tmpl/compare/MathewSachin-patch-1

I've not tested it. But, I think it should work. Please try it out and let me know.

**Comment by segfaultxavi** [comment]
Thanks a lot for such a quick response!
It **almost** works. The problem is that `{{>partials/classSubtitle}}` has a `\n` at the end, so the generated HTML looks like:
```
    <a href="#collapse-Fields^M
  " class="expander" data-toggle="collapse">^M
```
If I manually remove that extra line feed, it works. Do you know how to get rid of it?

**Comment by MathewSachin** [comment]
You could try copying [classSubtitle.tmpl.partial](https://github.com/dotnet/docfx/blob/v2.17.4/src/docfx.website.themes/common/partials/classSubtitle.tmpl.partial) from the default template into your template and removing all new lines from it (everything on single line).
This will override the default file.

**Comment by segfaultxavi** [comment]
I just used `{{id}}` instead of `{{>partials/classSubtitle}}` to fix it 😄 

My next question is how to make the sections appear in the collapsed state. Got any idea?

**Comment by MathewSachin** [comment]
Add class `collapse` on the div.

Also, when using `{{id}}` verify if it conflicts with other sections. I've faced a similar problem before.

**Comment by segfaultxavi** [comment]
The `collapse` class worked. Thanks again!

The possible `{{id}}` are `Fields`, `Methods`, `Properties`, `Implements`, etc. How could there be a conflict?

**Comment by MathewSachin** [comment]
If you've verified the values of `{{id}}` then its fine. I'm currently unable to test it myself so just wanted to confirm.

And, you're welcome!

**Comment by segfaultxavi** [comment]
Just for reference, I also had to change the expander class to `expander collapsed` so that the arrows are in sync with the initial state of the div.

A pleasure working with you!
