### ISSUE TITLE
Namespace: System.Dynamic.ExpandoObject

### ISSUE THREAD

**Issue by Mike-E-angelo** [MathewSachin/docfx-tmpl#2]
Greetings, investigating DocFX here and encountered your template which I have selected and have on display here:

https://mike-eee.github.io/ExtendedXmlSerializer/

However, funny thing when you go through all the classes, they all state they are in the `System.Dynamic.ExpandoObject` namespace.  Example class:

https://mike-eee.github.io/ExtendedXmlSerializer/api/ExtendedXmlSerializer.ExtensionMethodsForAttachedProperties.html

Using the default theme appears to report the expected value.  I am a total newb to DocFX, but thought I would report it here before I start spelunking to fix it on my end.  Any pointers on where to look would be appreciated as well.

In any case, thank you for making this theme! 👍

**Comment by MathewSachin** [comment]
Welḷ, quite a few versions of DocFX have been released after this template was made. So, I think this is related to a change in the default theme.

On looking into their theme, I found this:

https://github.com/dotnet/docfx/blob/c0d017b858d361b5ec351a3ddbd275d7536c9841/src/docfx.website.themes/default/partials/class.header.tmpl.partial#L45

```html
<h6><strong>{{__global.namespace}}</strong>: {{{namespace.specName.0.value}}}</h6>
```

Changing the following line in this theme might fix the issue:

https://github.com/MathewSachin/docfx-tmpl/blob/b26a800bd5c66268e22498eec35277b525b407b8/src/partials/class.header.tmpl.partial#L37

I'd be happy if you'd want to give it a try.

**Comment by Mike-E-angelo** [comment]
Ok cool!  Thank you for pointing the way.  I will see if I can get a PR cooked up here either today or tomorrow. 👍

**Comment by Mike-E-angelo** [comment]
Gah... I've become what I hate. 😆  Pet peeve of mine to have someone say they are going to do something and then NOT DO IT. 😁

I got tied up on a massive rabbit hole, but hey I know GitHub Actions now. 😅

Anyways, you were spot on!  I have submitted #3 for your review. 👍
